spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/randb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        #       show_sql: true
        format_sql: true

  